apiVersion: skaffold/v2beta15
kind: Config
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/skaffold-bazel
    bazel:
      target: //:skaffold_example.tar
profiles:
- name: remote
  build:
    googleCloudBuild:
      projectId: agmsb-k8s