apiVersion: skaffold/v2beta15
kind: Config
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/skaffold-bazel
    bazel:
      target: //:skaffold_example.tar
deploy:
  kustomize:
    paths:
    - https://github.com/agmsb/k8s-golden-manifests/gke-skaffold-bazel/resources