steps:
- id: skaffold-build
  name: "gcr.io/k8s-skaffold/skaffold:v1.23.0"
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      export SKAFFOLD_TAG=${SHORT_SHA}
      cd app
      skaffold build
-  id: demo-private-connectivity
   name: 'gcr.io/cloud-builders/curl'
   args: ['10.138.15.198:80']
options:
  workerPool: 'projects/agmsb-k8s/locations/us-west1/workerPools/loop-0'